import React from 'react';
import '../../App.css';
import Footer from '../Footer.js';

function GTAV() {
    return (
        <>
            <div>EÑE</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>GTAV</div>
            <div>EKISDE</div>
            <Footer />
        </>
    );
}

export default GTAV;
